### ISSUE TITLE
Autostart after first setup

### ISSUE THREAD

**Issue by krisproger** [jawikas/hamsterkombat#22]
Thank you for the good job! That repo is the best practices to knows how it works inside the tap apps (IMHO), but... ))
when i setup options at first time i want to launch script without questions in future.
What i mean:
at first app wrote options to config.json after setup and than always try to get settings from config
in main() core.py
```
    auto_upgrade = config.get('auto_upgrade', False)
    combo_upgrade = config.get('combo_upgrade', False)
    daily_cipher_on = config.get('daily_cipher_on', False)
    claim_key_on = config.get('claim_key_on', False)
    tasks_on = config.get('tasks_on', False)
    _method = config.get("upgrade_method", "1")
    taps_on = config.get("taps_on", False)
    promo_on = config.get("promo_on", False)
```
the second one is to setup autostart option in menu in choices and config read:
```
    autostart = config.get("autostart", False)
```
the last one is to check autostart option in while|try:
```
            if not autostart:
                choice = show_menu(auto_upgrade, taps_on, combo_upgrade, daily_cipher_on, claim_key_on, tasks_on, promo_on)
            else:
                choice = "0"
```

**Comment by jawikas** [comment]
as you want ! :)

**Comment by krisproger** [comment]
just as advice to improve app ;-)
