### ISSUE TITLE
An error occurred in the main loop

### ISSUE THREAD

**Issue by moewob** [jawikas/hamsterkombat#39]
```
An error occurred in the main loop: log() takes 1 positional argument but 2 were given
please wait until 00:00:07
```

**Comment by sacoq** [comment]
in line 105 of the file exceptions.py change the line to this one-
data = json.dumps({"taskId": "streak_days_special"})

**Comment by moewob** [comment]
> Can gets fixed by finding and changing this part on src/**init**.py **Original:**
> 
> ```
> def log(message, **kwargs):
>     global last_log_message
>     current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
>     flush = kwargs.pop('flush', False)
>     end = kwargs.pop('end', '\n')
>     if message != last_log_message:
>         print(f"{htm}[{current_time}] {message}", flush=flush, end=end)
>         last_log_message = message
> 
> def log_line():
>     print(pth + "~" * 60)
> ```
> 
> **Revised:**
> 
> ```
> def log(message, *args, **kwargs):
>     global last_log_message
>     current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
>     flush = kwargs.pop('flush', False)
>     end = kwargs.pop('end', '\n')
> 
>     # Join the message and any additional arguments into a single string
>     full_message = message.format(*args)
> 
>     if full_message != last_log_message:
>         print(f"[{current_time}] {full_message}", flush=flush, end=end)
>         last_log_message = full_message
> 
> def log_line():
>     print("~" * 60)
> ```

https://github.com/jawikas/hamsterkombat/pull/41#issuecomment-2330659066

**Comment by krisproger** [comment]
```
[2024-09-05 14:18:50] CEO of binance exchange
[2024-09-05 14:18:50] Daily streaks already claimed
[2024-09-05 14:18:50] Total 60 Energy available
[2024-09-05 14:18:51] boost on cooldown or unavailable
[2024-09-05 14:18:52] All task has been claimed successfully
[2024-09-05 14:18:52] No valid cipher or already claimed.
[2024-09-05 14:18:53] An error occurred in the main loop: '"name"'

```
its happening after upper fix (

**Comment by moewob** [comment]
> ```
> [2024-09-05 14:18:50] CEO of binance exchange
> [2024-09-05 14:18:50] Daily streaks already claimed
> [2024-09-05 14:18:50] Total 60 Energy available
> [2024-09-05 14:18:51] boost on cooldown or unavailable
> [2024-09-05 14:18:52] All task has been claimed successfully
> [2024-09-05 14:18:52] No valid cipher or already claimed.
> [2024-09-05 14:18:53] An error occurred in the main loop: '"name"'
> ```
> 
> its happening after upper fix (

https://github.com/jawikas/hamsterkombat/pull/40#issue-2506723264

**Comment by moewob** [comment]
FIXED
